//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tlAdvn.rc
//
#define ID_BUTTON_SET                   3
#define IDRESET                         3
#define ID_BUTTON_ADD                   4
#define ID_BUTTON_ADD2                  5
#define IDD_DIALOG_BINARY               134
#define IDD_DIALOG_CLUSTERSET           140
#define IDD_DIALOG_DISCRIMINANT         143
#define IDD_DIALOG_DISSET               144
#define IDC_BUTTON1                     1001
#define IDC_BUTTON_STATISTIC            1001
#define IDC_BUTTON_SURVIVALLT_OPTION    1001
#define IDC_BUTTON_SETTING              1001
#define IDC_BUTTON_SURVIVALKM_SELECTFACTOR 1001
#define IDC_BUTTON_SET                  1001
#define IDC_BTN_SELVAR                  1001
#define IDC_BUTTON_HELP                 1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_SURVIVALLT_EVENT     1002
#define IDC_EDIT_UPPER                  1008
#define IDC_EDIT_KAPPA                  1008
#define IDC_EDIT_PERIOD                 1008
#define IDC_RADIO2                      1012
#define ID_BUTTON_DEL                   1016
#define ID_BUTTON_DEL2                  1017
#define IDC_BUTTON_SURVIVALLT_RESET     1026
#define IDC_LIST_SELTABLE               1027
#define IDC_LIST_VARTABLE               1028
#define IDC_BUTTON_ADD                  1029
#define IDC_BUTTON_REMOVE               1030
#define IDC_BUTTON_DEL                  1031
#define IDC_BUTTON_ADD2                 1031
#define IDC_EDIT_REMOVAL                1032
#define IDC_EDIT_FACTNUM                1032
#define IDC_BUTTON_ADD3                 1032
#define IDC_EDIT_CONFIDENCE             1033
#define IDC_COMBO_EXTRACTMETHOD         1036
#define IDC_RADIO1                      1037
#define IDC_RADIO10                     1038
#define IDC_RADIO_XIEFANGCHA            1038
#define IDC_RADIO3                      1038
#define IDC_RADIO_EXTRACTSTANDARD       1039
#define IDC_COMBO_DISTANCE              1040
#define IDC_RADIO_TOMASH                1040
#define IDC_COMBO_POWER                 1041
#define IDC_RADIO_TOMASH2               1041
#define IDC_COMBO_FOMLIZEMETHOD         1042
#define IDC_COMBO_ROOT                  1043
#define IDC_COMBO_CLUSTMETHOD           1044
#define IDC_RADIO_ANAMETHOD             1045
#define IDC_RADIO_AUTO                  1045
#define IDC_EDIT_PRO                    1046
#define IDC_RADIO_MOV                   1046
#define IDC_LIST_INPUT                  1047
#define IDC_LIST_VAR                    1048
#define IDC_BUTTON_METHODSET            1050
#define IDC_RADIO_FACTORNUM             1056
#define IDC_RADIO_SCOREMETHOD           1058
#define IDC_RADIO6                      1059
#define IDC_RADIO7                      1060
#define IDC_RADIO8                      1061
#define IDC_RADIO9                      1062
#define IDC_RADIO_ROTATEMETHOD          1063
#define IDC_LIST_SURVIVALLT_FIELD       1063
#define IDC_EDIT_ENTRY                  1065
#define IDC_RADIO_METHOD                1066
#define IDC_EDIT_TEST                   1066
#define IDC_RADIO_COEFFICIENT           1067
#define IDC_BUTTON_SURVIVALLT_SELECTTIME 1077
#define IDC_BUTTON_SURVIVALLT_SELECTSTATUS 1078
#define IDC_LIST_INDENPVARTABLE         2001
#define IDC_COMBO_METHOD                2002
#define IDC_LIST_COVVARTABLE            2002
#define IDC_COMBO_PERIOD                2003
#define IDC_BUTTON_DEPEAND              2009
#define IDC_BUTTON_INDEPEND             2010
#define IDC_BUTTON_OBSERVE              2010
#define IDC_BUTTON_INDEPENDREMOVAL      2011
#define IDC_BUTTON_FACTOR               2011
#define IDC_BUTTON_INDEPEND2            2012
#define IDC_BUTTON_INDEPENDREMOVAL2     2013
#define IDD_DIALOG_CLUST                2014
#define IDC_BUTTON_REMOVAL              2014
#define IDC_LIST_DEPEND                 2016
#define IDD_DIALOG_FACTOR               2017
#define IDC_LIST_TOTALOBSERVE           2017
#define IDC_LIST_VARSOURSE              2018
#define IDD_DIALOG_EXTRACTION           2018
#define IDC_LIST_VARSEL                 2019
#define IDD_DIALOG_STEPWISE             2019
#define IDC_LIST_CATEGRERY              2019
#define IDC_LIST_FACTOR_VAR             2019
#define IDC_BUTTON_SEL                  2020
#define IDC_LIST_VARCOV                 2020
#define IDD_DIALOG_PROBIT               2020
#define IDC_BUTTON_UNSEL                2021
#define IDC_BUTTON_SEL2                 2022
#define IDC_BUTTON_UNSEL2               2023
#define IDD_DIALOG_ORDINAL              2024
#define IDC_LIST_VARSEL2                2024
#define IDC_LIST_RESPONSE               2029
#define IDC_BUTTON_REPONSE              2030
#define IDD_DIALOG_TIME                 2034
#define IDC_LIST1                       2037
#define IDC_LIST_SPECIFIED              2037
#define IDC_LIST_SURVIVALLT_TIME        2037
#define IDC_LIST_SURVIVALCOX_COVARIATES 2037
#define IDC_LIST_ALLVAR                 2037
#define IDC_LIST_SOURCE                 2037
#define IDC_LIST2                       2038
#define IDC_LIST_SURVIVALLT_STATUS      2038
#define IDC_LIST_SELVAR                 2038
#define IDC_LIST_DEST                   2038
#define IDC_LIST3                       2039
#define IDD_DIALOG_TIMESET              2043
#define IDD_DIALOG_CURVEREG             2046
#define IDC_LIST_COV                    2047
#define IDD_DIALOG_MULTIANOVA           2051
#define IDD_DLG_LINT_MULTIPLE_VALUE     2053
#define IDC_EDIT_MAXLAG1                2056
#define IDC_EDIT_AUTOREGRESSIONLADDER1  2057
#define IDC_EDIT_FORECAST               2058
#define IDC_EDIT_DIFFLADDER             2059
#define IDC_EDIT_AUTOREGRESSIONLADDER2  2060
#define IDC_EDIT_SLIDELADDER            2061
#define IDC_EDIT_START                  2062
#define IDC_EDIT_MAXLAG2                2063
#define IDC_COMBO_MOV                   2066
#define IDC_COMBO_SQURE_TYPE            2066
#define IDC_COMBO_SQUARESUM             2067
#define IDC_BUTTON3                     2068
#define IDC_COMBO_METH                  2069
#define IDC_RADIO_SEASON                2070
#define IDC_RADIO_X11                   2071
#define IDC_CHECK_LINEAR                2072
#define IDC_CHECK_Quad                  2073
#define IDC_CHECK_Compound              2074
#define IDC_CHECK_Growth                2075
#define IDC_CHECK_Exponential           2076
#define IDC_CHECK_Cubic                 2077
#define IDC_CHECK_S                     2078
#define IDC_CHECK_Inverse               2079
#define IDC_CHECK_Power                 2080
#define IDC_CHECK_Logistic              2081
#define IDC_CATEGORY_LABELS             2081
#define IDC_CHECK_Logarithmic           2082
#define IDC_BUTTON_MODEL                2082
#define IDC_RADIO_FULLFACT              2084
#define IDC_RADIO_CUSTOM                2085
#define IDC_COMBO_BUILD_ITERMS          2087
#define IDC_EDIT_DISTANCE               2088
#define IDC_EDIT_SOLARITY               2089
#define IDC_EDIT_LAMBDA                 4000
#define IDC_LIST_DECISION               4000
#define IDD_DIALOG_MULTANOVA_SETING     4001
#define IDC_EDIT_MAX                    4001
#define IDC_STATIC_1                    4002
#define IDD_DIALOG_NESTED               4002
#define IDC_LIST_SELECT                 4003
#define IDD_DIALOG_BLURRY               4003
#define IDC_EDIT_NUM                    4003
#define IDC_LIST_SELECTED               4004
#define IDD_DIALOG_PROGRESS             4004
#define IDC_STATIC_2                    4004
#define IDD_DIALOG_ROUTHSET             4005
#define IDC_RADIO_SPECIFIED             4005
#define IDC_COMBO_DIFFLADDER            4006
#define IDD_DIALOG_SETOUTPUT            4006
#define IDD_DIALOG_CLUSTSET             4007
#define IDC_BUTTON_OUPPUTSET            4008
#define IDC_CHECK_SCORE                 4008
#define IDC_CHECK_W                     4009
#define IDD_DIALOG_FACTORSTATISTIC      4009
#define IDC_CHECK_SHENGYU               4009
#define IDC_CHECK_T1                    4009
#define IDC_CHECK_T                     4010
#define IDC_CHECK_ZAISHENG              4010
#define IDC_CHECK_In1                   4010
#define IDC_CHECK_C1                    4011
#define IDC_CHECK_ANTIIMAGE             4011
#define IDD_DIALOG_DISCRIMIN            4011
#define IDC_CHECK_C2                    4012
#define IDC_CHECK_ANTIIMAGE2            4012
#define IDD_DIALOG_SURVIVALLT_DEFINEEVENT 4012
#define IDC_CHECK_TC                    4013
#define IDC_RADIO_CASE                  4013
#define IDD_DIALOG_DISCRIMINSET         4013
#define IDC_EDIT_MAXCOUNT               4014
#define IDD_DIALOG_PROBITSET            4014
#define IDC_CHECK_In                    4014
#define IDC_CHECK_TC2                   4014
#define IDC_EDIT_SURVIVALLT_MAXTIME     4015
#define IDD_DIALOG_CATEGREAGE           4015
#define IDC_CHECK_R                     4015
#define IDC_EDIT_SURVIVALLT_STEP        4016
#define IDC_CHECK_FL                    4016
#define IDC_RADIO_SURVIVALLT_SINGAL     4017
#define IDD_DIALOG_SEASON               4017
#define IDC_RADIO_SURVIVALLT_RANGE      4018
#define IDC_EDIT_SURVIVALLT_SINGLEVALUE 4019
#define IDD_DIALOG_X11                  4019
#define IDC_EDIT_SURVIVALLT_RANGEFROM   4020
#define IDC_EDIT_SURVIVALLT_RANGETO     4021
#define IDC_EDIT1                       4022
#define IDC_EDIT_C                      4022
#define IDC_EDIT_AUTOREG                4022
#define IDC_EDIT_TIME                   4022
#define IDC_EDIT_PERIODICITY            4022
#define IDC_EDIT_CONFID                 4022
#define IDC_EDIT2                       4023
#define IDC_EDIT_ITERATOR               4023
#define IDC_EDIT_MOVEAV                 4023
#define IDC_EDIT_ALPHA                  4023
#define IDC_EDIT_RANGE                  4023
#define IDC_RADIO_NATRUAL               4024
#define IDC_EDIT_DIFF                   4024
#define IDD_DIALOG_SET                  4024
#define IDC_EDIT_GAMMA                  4024
#define IDC_LIST_SURVIVALKM_FIELD       4025
#define IDC_EDIT_MAXITERATION           4025
#define IDD_PCOPTION                    4025
#define IDC_EDIT_DELTA                  4025
#define IDC_BUTTON_SURVIVALKM_SELECTTIME 4026
#define IDD_DIALOG_AR                   4026
#define IDC_EDIT_PHI                    4026
#define IDC_BUTTON_SURVIVALKM_SELECTSTATUS 4027
#define IDC_EDIT_PREDICTNUM             4027
#define IDC_BUTTON_SURVIVALKM_OPTION    4028
#define IDD_DIALOG_MA                   4028
#define IDC_BUTTON_SURVIVALKM_RESET     4029
#define IDC_EDIT_ALPHAFROM              4029
#define IDC_BUTTON_SURVIVALKM_EVENT     4030
#define IDC_EDIT_ALPHATO                4030
#define IDC_LIST_SURVIVALKM_STATUS      4031
#define IDC_EDIT_ALPHASTEP              4031
#define IDC_LIST_SURVIVALKM_FACTOR      4032
#define IDD_DIALOG_SMOOTHING            4032
#define IDC_EDIT_GAMMAFROM              4032
#define IDC_LIST_SURVIVALKM_TIME        4033
#define IDC_EDIT_GAMMATO                4033
#define IDC_EDIT_GAMMASTEP              4034
#define IDC_LIST_SURVIVALCOX_FIELD      4035
#define IDC_EDIT_DELTAFROM              4035
#define IDC_LIST_SURVIVALCOX_TIME       4036
#define IDC_EDIT_DELTATO                4036
#define IDC_BUTTON_SURVIVALCOX_SELECTTIME 4037
#define IDC_EDIT_DELTASTEP              4037
#define IDC_BUTTON_SURVIVALCOX_SELECTSTATUS 4038
#define IDC_EDIT_PHIFROM                4038
#define IDC_LIST_SURVIVALCOX_STATUS     4039
#define IDC_EDIT_PHITO                  4039
#define IDC_BUTTON_SURVIVALCOX_RESET    4040
#define IDC_EDIT_PHISTEP                4040
#define IDC_BUTTON_SURVIVALCOX_OPTION   4041
#define IDC_BUTTON_SURVIVALCOX_EVENT    4042
#define IDC_BUTTON_SURVIVALCOX_SELECTCOVARIATES 4043
#define IDC_RADIO_CALCULATE             4044
#define IDC_RADIO_CONST                 4045
#define IDC_CHECK_KMO                   4046
#define IDC_CHECK_CLUSTERINFO           4047
#define IDC_COMBO1                      4048
#define IDC_CHECK_PEDIGREE              4048
#define IDC_STATIC1                     4049
#define IDC_COMBO_SEASON                4049
#define IDC_STATIC2                     4050
#define IDC_CHECK_BASELNE               4051
#define IDC_STATIC3                     4051
#define IDC_RADIO_MISSMETHOD            4052
#define IDC_RADIO_MISSING               4053
#define IDC_STATIC4                     4053
#define IDC_COMBO_MOVE                  4054
#define IDC_CHECK_CONSTANT              4055
#define IDC_COMBO_PARAM                 4056
#define IDC_STATIC_3                    4057
#define IDC_EDIT_FORCAST                4058
#define IDD_DLGMODELIDENTITY_DIALOG     4059
#define IDC_EDIT_PCFACTNUM              4060
#define IDC_EDIT_PCPRO                  4061
#define IDC_RADIO_PCFACTORNUM           4062
#define IDC_RADIO_PCEXTRACTSTANDARD     4063
#define IDC_RADIO_PCANAMETHOD           4064
#define IDC_RADIO_PCXIEFANGCHA          4065
#define IDC_COMBO_TREND                 4066
#define IDC_SHOWPREDICT                 4067
#define IDC_RADALPHAV                   4068
#define IDC_RADALPHAGRID                4069
#define IDC_RADGAMMAV                   4070
#define IDC_CHECK_RESIDUE               4070
#define IDC_RADGAMMAGRID                4071
#define IDC_RADDELTAV                   4072
#define IDC_CHECK_PREDICT               4072
#define IDC_RADDELTAGRID                4073
#define IDC_CHECK_ChartLine             4073
#define IDC_RADPHIV                     4074
#define IDC_CHECK_ChartScatterPlot      4074
#define IDC_CHECK_OUTPUT                4074
#define IDC_RADPHIGRID                  4075
#define IDC_CHECK_ChartScatterPlot2     4075
#define IDC_SHOWBESTMODELS              4076
#define IDC_CHECK_ARMODEL               4077
#define IDC_CHECK_MAMODEL               4078
#define IDC_CHECK_ARMAMODEL             4081
#define IDC_CHECK_DIFF                  4085
#define IDC_STATIC_DIFF                 4087
#define IDC_PROGRESS1                   5000
#define IDC_PROGRESS2                   5001
#define IDC_STATIC_INDEX                5002
#define IDM_TABLE_EXPORT                5010
#define IDC_BtnHelp                     21069
#define IDD_DIALOG_SURVIVAL_LIFETABLES  22160
#define IDD_DIALOG_SURVIVAL_KAPLANMEIER 22161
#define IDD_DIALOG_SURVIVAL_COXREGRESSION 22162

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4035
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4088
#define _APS_NEXT_SYMED_VALUE           4060
#endif
#endif
