/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class Interface */

#ifndef _Included_Interface
#define _Included_Interface
#ifdef __cplusplus
#endif
#ifdef _UNIX
	#ifdef _LINUX
		#include "jni_linux/jni.h"
	#endif
#else
	#include "INCLUDE/jni.h"
#endif
#endif
