include ../Makefile.h

SOURCES		= tlBase.cpp
OBJECTS		= $(SOURCES:.cpp=.o)
MODULE		= $(FINAL_DIR)/tlbase.so

.PHONY:         all clean
all:       first     $(MODULE)

first:
	mkdir -p $(FINAL_DIR)		


$(MODULE):  $(OBJECTS)	
	$(CXX) -o $@ $(OBJECTS)	-shared -L$(FINAL_DIR) -ltlpublic -ltlcpknl -ltldbif -ltlresult -lpthread -ldl -ltlarithif
		
%.o: %.cpp
	$(CXX) -c $(CXXFLAGS) -fPIC -o $@ $< 

clean:
	rm -f $(OBJECTS) $(MODULE) 
